Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")
Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")
Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")
Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")
Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")
Giraffe.create!(name: "steven", description: "he's a cool giraffe, but he thinks people are leaves, so he wont stop biting them, which is proving to be problematic in a myriad of ways")
Giraffe.create!(name: "giraffey", description: "Just like the default giraffe")
Giraffe.create!(name: "bobby", description: "A very odd giraffe, deer shaped and also brown. not sure if he's actually a giraffe")